version: '3.8'

services:
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./www:/app/www
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/minecraftpanel
      - JWT_SECRET=borja_super_secreto

  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
